name: CI

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      NODE_ENV: test
      CONTENTFUL_SPACE_ID: dummy
      CONTENTFUL_ACCESS_TOKEN: dummy
      CONTENTFUL_ENVIRONMENT: master
      CONTENTFUL_CONTENT_TYPE: product
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: app

    strategy:
      matrix:
        node: [20.x] 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test (unit) + coverage
        run: npm run test -- --ci --runInBand --coverage

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: Build (type-check + transpile)
        run: npm run build
